// iupac-adapter.js
// ─────────────────────────────────────────────────────────────────────────────
// IUPAC-1: IUPAC name lookup in both directions.
//
//   Structure → Name:
//     Given a user input (formula or name), resolve to IUPAC name via the
//     local cache (window.IUPAC_CACHE, generated by build-iupac-cache.js)
//     or live CACTVS fallback.
//
//   Name → Structure:
//     Given an IUPAC name, resolve to a chemical formula via live CACTVS.
//     The formula is fed back into our existing parser.
//
// CACTVS internally uses OPSIN (Cambridge) for name parsing, so arbitrary
// systematic IUPAC names work at the CACTVS endpoint. Reference:
// https://cactus.nci.nih.gov/blog/?cat=10
//
// Dependencies:
//   - jsmol-adapter.js (for NAME_MAP and lookupName)
//   - window.IUPAC_CACHE (optional; adapter works without it, just slower)
// ─────────────────────────────────────────────────────────────────────────────

const IUPAC = (function () {

  const CACTVS_BASE = 'https://cactus.nci.nih.gov/chemical/structure';
  const REQUEST_TIMEOUT_MS = 10000;

  // ── Cache lookup (structure → name) ──────────────────────────────────
  // The build script writes js/iupac-cache/manifest.js which assigns
  // window.IUPAC_CACHE = { "<cactvs-name>": "<iupac-name>", ... }.
  // This gives us synchronous cache access at runtime.

  // Returns the cached IUPAC name for a CACTVS query name, or null.
  function _cachedIupacName(cactvsName) {
    if (typeof window === 'undefined') return null;
    const cache = window.IUPAC_CACHE;
    if (!cache || typeof cache !== 'object') return null;
    return cache[cactvsName] || null;
  }

  // ── Structure → IUPAC name ───────────────────────────────────────────
  // Resolves via: NAME_MAP (user input → CACTVS query) → local cache → null.
  // Callers who want a live fallback can use getIupacNameAsync below.
  function getIupacName(userInput) {
    if (typeof JSMOL === 'undefined' || !JSMOL.lookupName) return null;
    const cactvsName = JSMOL.lookupName(userInput);
    if (!cactvsName) return null;
    return _cachedIupacName(cactvsName);
  }

  // Async variant: checks cache first, falls back to live CACTVS.
  // Returns a Promise that resolves to the IUPAC name, or null if not found.
  async function getIupacNameAsync(userInput) {
    const cached = getIupacName(userInput);
    if (cached) return cached;

    if (typeof JSMOL === 'undefined' || !JSMOL.lookupName) return null;
    const cactvsName = JSMOL.lookupName(userInput) || userInput;
    return _fetchIupacFromCactvs(cactvsName);
  }

  // Live CACTVS lookup for IUPAC name. Used when the cache doesn't have
  // this molecule (e.g., new molecule added since last build, or the build
  // skipped this one).
  async function _fetchIupacFromCactvs(cactvsQuery) {
    if (typeof fetch !== 'function') return null;
    const url = CACTVS_BASE + '/' + encodeURIComponent(cactvsQuery) + '/iupac_name';
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
      const response = await fetch(url, { signal: controller.signal });
      clearTimeout(timeout);
      if (!response.ok) return null;
      const text = (await response.text()).trim();
      if (!text || text.toLowerCase().includes('<html')) return null;
      const firstLine = text.split(/\r?\n/)[0].trim();
      return firstLine || null;
    } catch (_) {
      return null;
    }
  }

  // ── Name → Structure ─────────────────────────────────────────────────
  // Detect whether the user's input looks like an IUPAC name (rather than
  // a formula). This is a permissive heuristic — we only bother trying
  // CACTVS name resolution if the input has features typical of IUPAC
  // names. Formulas like "H2O" or "C6H6" will be rejected here.
  //
  // Positive signals (input looks name-like):
  //   - Contains lowercase letter sequences longer than 4 chars (e.g.,
  //     "propan", "benzene", "methyl")
  //   - Contains known IUPAC suffixes (-ol, -al, -one, -oic, -ene, -yne,
  //     -amine, -nitrile, -yl, -ic acid, -anhydride)
  //   - Contains hyphen-bounded locants like "2-" or "1,4-"
  //   - Contains spaces (multi-word names like "acetic acid")
  //
  // Negative signals (input looks like a formula):
  //   - Uppercase-first atomic-style patterns (H2O, C6H12O6, SO4{-2})
  //   - Charge notation {+1} / {-2}
  //
  // Returns true if we should attempt name-to-structure resolution.
  function looksLikeIupacName(input) {
    if (typeof input !== 'string' || !input.trim()) return false;
    const s = input.trim();

    // Charge notation → definitely a formula
    if (/\{[+\-]\d*\}/.test(s)) return false;
    if (/\{[+\-]\}/.test(s))    return false;

    // Has a space with lowercase — likely a name (e.g. "acetic acid")
    if (/\s/.test(s) && /[a-z]/.test(s)) return true;

    // Known IUPAC suffixes and substrings (case-insensitive)
    const namePatterns = [
      /\b\w+(ane|ene|yne)\b/i,             // methane, ethene, propyne
      /\b\w+(ol|al|one|oate|oic)\b/i,      // ethanol, propanal, acetone
      /\boic\s*acid\b/i,                   // acetic acid, oic acid
      /\b\w+amine\b/i,                     // methylamine, aniline-family
      /\b\w+aniline\b|\baniline\b/i,       // aniline itself
      /\b\w+pyridine\b|\bpyridine\b/i,     // pyridine
      /\b\w+(furan|pyrrole|thiophene)\b/i, // heterocycles
      /\b\w+nitrile\b/i,                   // acetonitrile
      /\b\w+oxide\b/i,                     // ethylene oxide
      /\b\w+aldehyde\b/i,                  // acetaldehyde, benzaldehyde
      /\b\w+anoate\b|\b\w+ylate\b/i,       // ester forms
      /-\d+-/,                             // locants like "2-methyl-1-"
      /^\d+,\d+-/,                         // "1,4-" prefix
      /^(alpha|beta|ortho|meta|para|cis|trans|n)-/i,
      /\bmethyl\b|\bethyl\b|\bpropyl\b|\bbutyl\b|\bphenyl\b/i
    ];
    if (namePatterns.some(p => p.test(s))) return true;

    // Fallback: an all-lowercase word of 5+ characters with no digits is
    // almost certainly a chemical name, not a formula. Formulas tend to
    // be short and mixed-case (H2O, CH4, NaCl) or have numbers (C6H6).
    // This catches things like "aniline", "pyridine", "toluene" that
    // don't match the suffix patterns above.
    if (/^[a-z]{5,}$/.test(s)) return true;

    return false;
  }

  // Given an IUPAC name, ask CACTVS for the chemical formula.
  // Returns a Promise resolving to { ok, formula, error? }.
  async function resolveNameToFormula(iupacName) {
    if (typeof fetch !== 'function') {
      return { ok: false, error: 'Network unavailable.' };
    }
    const url = CACTVS_BASE + '/' + encodeURIComponent(iupacName) + '/formula';
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
      const response = await fetch(url, { signal: controller.signal });
      clearTimeout(timeout);
      if (!response.ok) {
        return { ok: false, error: 'CACTVS returned HTTP ' + response.status };
      }
      const text = (await response.text()).trim();
      if (!text) {
        return { ok: false, error: 'CACTVS returned empty response' };
      }
      if (text.toLowerCase().includes('<html')) {
        return { ok: false, error: 'CACTVS could not resolve that name' };
      }
      const formula = text.split(/\r?\n/)[0].trim();
      return { ok: true, formula };
    } catch (err) {
      if (err.name === 'AbortError') {
        return { ok: false, error: 'CACTVS request timed out' };
      }
      return { ok: false, error: err.message || String(err) };
    }
  }

  return {
    getIupacName,            // sync; null if not cached
    getIupacNameAsync,       // async; falls back to live CACTVS
    looksLikeIupacName,      // heuristic for input detection
    resolveNameToFormula,    // async; CACTVS name → formula
    _cachedIupacName         // exported for tests
  };
})();

// Expose for Node tests
if (typeof module !== 'undefined' && module.exports) {
  module.exports = IUPAC;
}
